MyMarket/Web/MyMarket.Web/Models/Ad/AdCreateViewModel.cs
namespace MyMarket.Web.Models.Ad
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;

    using Category;
    using Common;
    using Common.Validators;
    using Data.Models;
    using Infrastructure.Mapping;

    public class AdCreateViewModel : IMapFrom<Ad>
    {
        [Required]
        [MinLength(ValidationConstants.NAME_MIN_LENGTH)]
        [MaxLength(ValidationConstants.NAME_MAX_LENGTH)]
        public string Title { get; set; }

        [Required]
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        [MinLength(ValidationConstants.CONTENT_MIN_LENGTH)]
        [MaxLength(ValidationConstants.CONTENT_MAX_LENGTH)]
        public string Description { get; set; }

        [Required]
        [Range(0, int.MaxValue)]
        [DisplayFormat(DataFormatString = "{0:F2}", ApplyFormatInEditMode = true)]
        public decimal Price { get; set; }

        [Required]
        [Display(Name = "Category")]
        public int CategoryId { get; set; }

        public IEnumerable<CategoryViewModel> Categories { get; set; }

        [Required]
        [Display(Name = "Main Picture")]
        [CustomValidation(typeof(AdImageValidator), "ValidateImage")]
        public HttpPostedFileBase MainPicture { get; set; }

        [Display(Name = "Other Pictures")]
        [CustomValidation(typeof(AdImageValidator), "ValidateImages")]
        public IEnumerable<HttpPostedFileBase> OtherPictures { get; set; }
    }
}

MyMarket/Web/MyMarket.Web/Models/Ad/AdViewModel.cs
namespace MyMarket.Web.Models.Ad
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    using AutoMapper;

    using Comments;
    using Data.Models;
    using Infrastructure.Mapping;

    public class AdViewModel : IMapFrom<Ad>, IHaveCustomMappings
    {
        public int Id { get; set; }

        public DateTime CreatedOn { get; set; }

        public string Title { get; set; }

        public string Description { get; set; }

        public string UrlPath { get; set; }

        public decimal Price { get; set; }

        public string Category { get; set; }

        public int Visits { get; set; }

        public int Likes { get; set; }

        public IEnumerable<CommentViewModel> Comments { get; set; }

        public void CreateMappings(IConfiguration config)
        {
            config.CreateMap<Ad, AdViewModel>()
                .ForMember(x => x.UrlPath, opt => opt.MapFrom(x => x.MainImage.UrlPath))
                .ForMember(x => x.Category, opt => opt.MapFrom(x => x.Category.Name))
                .ForMember(x => x.Visits, opt => opt.MapFrom(x => x.Visits.Count))
                .ForMember(x => x.Likes, opt => opt.MapFrom(x => x.Likes.Count))
                .ForMember(x => x.Comments, opt => opt.MapFrom(x => x.Comments.Where(y => !y.IsDeleted).OrderByDescending(y => y.CreatedOn)));
        }
    }
}

MyMarket/Web/MyMarket.Web/Models/Ad/AdsSearchResultViewModel.cs
namespace MyMarket.Web.Models.Ad
{
    using System.Collections.Generic;

    using Infrastructure.Mapping;

    public class AdsSearchResultViewModel : IMapFrom<AdViewModel>
    {
        public IEnumerable<AdViewModel> Ads { get; set; }

        public int CurrentPage { get; set; }

        public int TotalPages { get; set; }
    }
}

MyMarket/Web/MyMarket.Web/Models/Ad/AdsSearchViewModel.cs
namespace MyMarket.Web.Models.Ad
{
    using System.Collections.Generic;

    using Common;

    public class AdsSearchViewModel
    {
        public AdsSearchViewModel()
        {
            if (string.IsNullOrEmpty(this.SortBy))
            {
                this.SortBy = NativeConstants.AdsInitialOrderBy;
            }

            if (string.IsNullOrEmpty(this.SortType))
            {
                this.SortType = NativeConstants.AscendingSortAds;
            }
        }

        public string SearchWord { get; set; }

        public IEnumerable<int> ChosenCategoriesIds { get; set; }

        public string SortBy { get; set; }

        public string SortType { get; set; }
    }
}

MyMarket/Web/MyMarket.Web/Models/Home/AdViewModel.cs
namespace MyMarket.Web.Models.Home
{
    using System;

    using AutoMapper;

    using Data.Models;
    using Infrastructure.Mapping;

    public class AdViewModel : IMapFrom<Ad>, IHaveCustomMappings
    {
        public DateTime CreatedOn { get; set; }

        public string Title { get; set; }

        public string Description { get; set; }

        public byte[] Picture { get; set; }

        public decimal Price { get; set; }

        public string Category { get; set; }

        public int Visits { get; set; }

        public int Likes { get; set; }

        public int Comments { get; set; }

        public void CreateMappings(IMapperConfiguration config)
        {
            config.CreateMap<Ad, AdViewModel>()
                .ForMember(x => x.Category, opt => opt.MapFrom(x => x.Category.Name))
                .ForMember(x => x.Visits, opt => opt.MapFrom(x => x.Visits.Count))
                .ForMember(x => x.Likes, opt => opt.MapFrom(x => x.Likes.Count))
                .ForMember(x => x.Comments, opt => opt.MapFrom(x => x.Comments.Count));
        }
    }
}

MyMarket/Web/MyMarket.Web/Controllers/AdsController.cs
namespace MyMarket.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.IO;
    using System.Web;
    using System.Web.Mvc;

    using AutoMapper;

    using Bytes2you.Validation;

    using Microsoft.AspNet.Identity;

    using Attributes;
    using Common;
    using Data.Models;
    using Infrastructure.Mapping;
    using Models.Ad;
    using Models.Category;
    using Services.Data.Contracts;
    using Services.FileSystem.Contracts;

    public class AdsController : BaseController
    {
        private readonly IAdsService adsService;
        private readonly ICategoriesService categoriesService;
        private readonly IFileSystemService fileSystemService;
        private readonly IImagesService imagesService;

        public AdsController(
            IAdsService adsService,
            ICategoriesService categoriesService,
            IFileSystemService fileSystemService,
            IImagesService imagesService)
        {
            Guard.WhenArgument(adsService, nameof(adsService)).IsNull().Throw();
            Guard.WhenArgument(categoriesService, nameof(categoriesService)).IsNull().Throw();
            Guard.WhenArgument(fileSystemService, nameof(fileSystemService)).IsNull().Throw();
            Guard.WhenArgument(imagesService, nameof(imagesService)).IsNull().Throw();

            this.adsService = adsService;
            this.categoriesService = categoriesService;
            this.fileSystemService = fileSystemService;
            this.imagesService = imagesService;
        }

        [HttpGet]
        [Authorize]
        public ActionResult Post()
        {
            return this.View(new AdCreateViewModel()
            {
                Categories = this.GetCategories()
            });
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Post(AdCreateViewModel createModel)
        {
            if (!this.ModelState.IsValid)
            {
                createModel.Categories = this.GetCategories();
                return this.View(createModel);
            }

            Image mainImage = this.ProcessImage(createModel.MainPicture);

            Ad adToCreate = Mapper.Map<Ad>(createModel);
            adToCreate.UserId = this.User.Identity.GetUserId();
            adToCreate.MainImageId = mainImage.Id;
            adToCreate.Images = this.ProcessImages(createModel.OtherPictures);

            int adId = this.adsService.Add(adToCreate);

            return RedirectToAction($"{adId}");
        }

        [HttpGet]
        public ActionResult Index()
        {
            return this.View(this.GetCategories());
        }

        [HttpGet]
        public ActionResult Get(int id)
        {
            if (id <= ValidationConstants.INVALID_ID)
            {
                return this.View("AdError");
            }

            var adById = this.adsService.GetAsQueryable(id)
                .To<AdViewModel>()
                .FirstOrDefault();

            if (adById == null)
            {
                return this.View("AdError");
            }

            return this.View(adById);
        }

        [HttpGet]
        [ChildActionOnly]
        public ActionResult InitialAds()
        {
            return this.Search(new AdsSearchViewModel(), NativeConstants.ADS_START_PAGE);
        }

        [HttpPost]
        [AjaxOnly]
        public PartialViewResult SearchAds(AdsSearchViewModel searchModel, int? page)
        {
            int actualPage = page ?? NativeConstants.ADS_START_PAGE;
            Guard.WhenArgument(actualPage, nameof(actualPage)).IsLessThan(NativeConstants.ADS_START_PAGE).Throw();

            return this.Search(searchModel, actualPage);
        }

        private PartialViewResult Search(AdsSearchViewModel search, int page)
        {
            Guard.WhenArgument(page, nameof(page)).IsLessThan(NativeConstants.ADS_START_PAGE).Throw();

            int allAdsCount = this.adsService.All().Count();
            int totalPages = (int)Math.Ceiling(allAdsCount / (decimal)NativeConstants.AdsPerPage);

            var ads = this.adsService
                .Search(search.SearchWord, search.ChosenCategoriesIds, search.SortBy, search.SortType, page)
                .To<AdViewModel>()
                .ToList();

            var adsListViewModel = new AdsSearchResultViewModel()
            {
                Ads = ads,
                CurrentPage = page,
                TotalPages = totalPages
            };

            return this.PartialView("_AdsPartial", adsListViewModel);
        }

        private IEnumerable<CategoryViewModel> GetCategories()
        {
            return this.Cache.Get(
                "categories",
                () => this.categoriesService.All()
                    .OrderBy(c => c.Name)
                    .To<CategoryViewModel>()
                    .ToList(),
                15 * 60);
        }

        private ICollection<Image> ProcessImages(IEnumerable<HttpPostedFileBase> images)
        {
            ICollection<Image> result = new List<Image>();

            foreach (var image in images)
            {
                if (image != null)
                {
                    Image savedImage = this.ProcessImage(image);
                    result.Add(savedImage);
                }
            }

            return result;
        }

        private Image ProcessImage(HttpPostedFileBase image)
        {
            string path = this.Server.MapPath(NativeConstants.IMAGES_PATH);
            string urlPath = this.fileSystemService.SaveImage(image, path);

            var imageToSave = new Image()
            {
                FileExtension = Path.GetExtension(image.FileName),
                OriginalFileName = image.FileName,
                UrlPath = urlPath
            };

            this.imagesService.Add(imageToSave);

            return imageToSave;
        }
    }
}

MyMarket/Web/MyMarket.Web/Controllers/CommentsController.cs
using System.Net;
using System.Web.Mvc;

using AutoMapper;

using Bytes2you.Validation;

using Microsoft.AspNet.Identity;

using MyMarket.Data.Models;
using MyMarket.Services.Data.Contracts;
using MyMarket.Web.Attributes;
using MyMarket.Web.Models.Comments;

namespace MyMarket.Web.Controllers
{
    public class CommentsController : Controller
    {
        private readonly ICommentsService commentsService;

        public CommentsController(ICommentsService commentsService)
        {
            Guard.WhenArgument(commentsService, nameof(commentsService)).IsNull().Throw();

            this.commentsService = commentsService;
        }

        [HttpPost]
        [AjaxOnly]
        public PartialViewResult Post(string content, int adId)
        {
            var comment = new Comment()
            {
                Content = content,
                AdId = adId,
                UserId = this.User.Identity.GetUserId()
            };

            this.commentsService.Add(comment);

            var viewModel = Mapper.Map<CommentViewModel>(comment);
            viewModel.Username = this.User.Identity.Name;

            return this.PartialView("_CommentPartial", viewModel);
        }

        [HttpPost]
        [AjaxOnly]
        public HttpStatusCode Update(int id, string content)
        {
            Comment comment = this.commentsService.Get(id);

            if (comment != null)
            {
                comment.Content = content;
                this.commentsService.Update(id, comment);

                return HttpStatusCode.OK;
            }

            return HttpStatusCode.NotFound;
        }

        [HttpPost]
        [AjaxOnly]
        public HttpStatusCode Delete(int id)
        {
            Comment comment = this.commentsService.Delete(id);

            if (comment.IsDeleted)
            {
                return HttpStatusCode.OK;
            }

            return HttpStatusCode.NotFound;
        }
    }
}

MyMarket/Web/MyMarket.Web/Views/Ads/AdError.cshtml
@{
    ViewBag.Title = "Not Found";
}

<div class="container main-content">
    <h3 class="text-danger">Sorry! The content you are looking for was not found.</h3>
</div>

MyMarket/Web/MyMarket.Web/Views/Ads/Create.cshtml
@using MyMarket.Common;
@using MyMarket.Web.Models.Ad

@model AdCreateViewModel
@{
    ViewBag.Title = "Create Ad";
}

@if (this.User.Identity.IsAuthenticated)
{
    <h2>@ViewBag.Title</h2>

    using (Html.BeginForm("Create", "Ads", FormMethod.Post, new { id = "CreateAdForm", @class = "form-horizontal", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary("", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(a => a.Title, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(a => a.Title, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter title..." }})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(a => a.CategoryId, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.CategoryId, new SelectList(Model.Categories, "Id", "Name", 1), new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(a => a.Price, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(a => a.Price, new { htmlAttributes = new { @class = "form-control", @Value = "0.00", placeholder = "Enter price, e.g. 0.00 " }})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(a => a.Description, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(a => a.Description, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter description..." }})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(a => a.MainPicture, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(a => a.MainPicture, new { type = "file" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(a => a.OtherPictures, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                <div class="input-group">
                    <p>
                        @Html.TextBoxFor(a => a.OtherPictures, new { type = "file" })
                        @Html.TextBoxFor(a => a.OtherPictures, new { type = "file" })
                        @Html.TextBoxFor(a => a.OtherPictures, new { type = "file" })
                    </p>
                    <p>
                        <strong>
                            Allowed formats:
                            @ValidationConstants.JpgImage,
                            @ValidationConstants.JpegImage,
                            @ValidationConstants.PngImage,
                            @ValidationConstants.GifImage
                        </strong>
                        <br />
                        <strong>Maximum size: @ValidationConstants.AdImageContentLengthInKilobytes kb</strong>
                    </p>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-5 col-md-6">
                <input type="submit" class="btn btn-primary" value="Create" />
                <input type="button" class="btn btn-default" value="Clear" />
            </div>
        </div>
    }
}
else
{
    <div class="alert alert-info" role="alert">
        <i class="glyphicon glyphicon-remove-sign"></i>
        <strong>You are unauthorized!</strong> Please log into your acount first.
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyMarket/Web/MyMarket.Web/Views/Ads/Get.cshtml
@using System.Globalization
@using System.IO;

@using MyMarket.Common;
@using MyMarket.Web.Models.Ad

@model AdViewModel
@{
    ViewBag.Title = Model.Title;
}

<h3>@ViewBag.Title</h3>

<div class="container single_top main-content">
    @if (TempData["Addition"] != null)
    {
        <div class="alert alert-success" role="alert">
            @TempData["Addition"]
        </div>
    }

    <div class="row">
        <div class="col-md-3 ad-image">
            <img src="@Url.Content(NativeConstants.IMAGES_PATH + Path.GetFileName(Model.UrlPath))" alt="Ad Image" />
        </div>
        <div class="col-md-9">
            <p class="published-ad">Price: <span>@Model.Price</span></p>
            <div class="ad-description">@Html.Raw(Model.Description)</div>
            <p class="published-ad">Published on: @Model.CreatedOn.ToString("dd/MMMM/yyyy", CultureInfo.InvariantCulture)</p>
        </div>
    </div>

    <div class="row">
        <div class="form-group">
            <h5>@Model.Comments.Count() Comments</h5>

            @if (this.User.Identity.IsAuthenticated)
            {
                <div id="PostCommentDiv">
                    @using (this.Ajax.BeginForm("Post", "Comments", null,
                    new AjaxOptions()
                    {
                        HttpMethod = "POST",
                        UpdateTargetId = "Comments",
                        OnComplete = "onAjaxRequestComplete",
                        InsertionMode = InsertionMode.InsertBefore
                    },
                    new { }))
                    {
                        <div>
                            <textarea id="PostComment" maxlength="1000" name="content" placeholder="Add a comment..."></textarea>
                            <input type="hidden" name="adId" value="@Model.Id" />
                            <input type="submit" class="btn btn-primary post-comment-button" value="Comment" />
                        </div>
                    }
                </div>
            }
            else
            {
                @Html.Partial("_UnauthorizedUserPartial", "Please login into your account in order to comment the ad.")
            }

            <div id="Comments">
                @foreach (var comment in Model.Comments)
                {
                    @Html.Partial("_CommentPartial", comment)
                }
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="EditCommentModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Confirmation</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="CommentContent" class="col-form-label">Comment:</label>
                    <textarea class="form-control" id="CommentContent"></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="UpdateCommentBtn" class="btn btn-primary" data-dismiss="modal">Update</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="DeleteCommentModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Confirmation</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this comment?</p>
            </div>
            <div class="modal-footer">
                <button type="button" id="DeleteCommentBtn" class="btn btn-primary" data-dismiss="modal">Delete</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<input type="hidden" id="CommentId" />

@section Scripts {
<script>
        function onAjaxRequestComplete() {
            $('#PostComment').val('');
        }

        $('#Comments').on('click', '.glyphicon-edit', function () {
            var id = $(this).attr('data-id');
            var content = $(this).attr('data-content');

            $('#CommentId').val(id);
            $('#CommentContent').val(content);
            $('#EditCommentModal').modal();
        });

        $('#Comments').on('click', '.glyphicon-remove-circle', function () {
            var id = $(this).attr('data-id');

            $('#CommentId').val(id);
            $('#DeleteCommentModal').modal();
        });

        $('#UpdateCommentBtn').on('click', function () {
            var id = $('#CommentId').val();
            var content = $('#CommentContent').val();

            $.ajax({
                type: 'POST',
                url: '@(Url.Action("Update", "Comments"))',
                data: {
                    id: id,
                    content: content
                },
                success: function (response) {
                    $('#Comment-' + id + ' .comment-content').html(content);
                },
                error: function (response) {
                    alert('Unable to update comment');
                    console.log(response);
                }
            });
        });

        $('#DeleteCommentBtn').on('click', function () {
            var id = $('#CommentId').val();

            $.ajax({
                type: 'POST',
                url: '@(Url.Action("Delete", "Comments"))',
                data: { id: id },
                success: function (response) {
                    $('#Comment-' + id).remove();
                },
                error: function (response) {
                    alert('Unable to delete comment');
                    console.log(response);
                }
            });
        });
</script>
}

MyMarket/Web/MyMarket.Web/Views/Ads/Index.cshtml
@using MyMarket.Web.Models.Category

@model IEnumerable<CategoryViewModel>
@{
    ViewBag.Title = "Search Ads";
}

<h2>Ads</h2>

<div class="container main-content">
    <div class="row">
        @using (this.Ajax.BeginForm("SearchAds", null,
                new AjaxOptions()
                {
                    HttpMethod = "POST",
                    UpdateTargetId = "SearchResults",
                    InsertionMode = InsertionMode.Replace,
                    OnBegin = "onAjaxRequestBegin",
                    OnComplete = "onAjaxRequestComplete"
                },
                new { id = "SearchForm", @class = "form-max-width" }))
        {
            <div class="form-group">
                <input type="text" id="SearchField" name="SearchWord" class="form-control inline-block" placeholder="Search" />
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>

            <ul class="sort-ads-list sort-by-category">
                <li class="sort-text-li">Sort:</li>
                <li>
                    <label for="Date">Date</label>
                    <input id="Date" type="radio" name="SortBy" checked="checked" value="CreatedOn">
                </li>
                <li>
                    <label for="Price">Price</label>
                    <input id="Price" type="radio" name="SortBy" value="Price">
                </li>
                <li>
                    <label for="Visits">Visits</label>
                    <input id="Visits" type="radio" name="SortBy" value="Visits">
                </li>
                <li>
                    <label for="Likes">Likes</label>
                    <input id="Likes" type="radio" name="SortBy" value="Likes">
                </li>
                <li>
                    <label for="Comments">Comments</label>
                    <input id="Comments" type="radio" name="SortBy" value="Comments">
                </li>
            </ul>
            
            <ul class="sort-ads-list sort-by-type">
                <li class="sort-text-li">Type:</li>
                <li>
                    <label for="Ascending">Ascending</label>
                    <input id="Ascending" type="radio" name="SortType" checked="checked" value="Ascending">
                </li>
                <li>
                    <label for="Descending">Descending</label>
                    <input id="Descending" type="radio" name="SortType" value="Descending">
                </li>
            </ul>

            <div class="col-md-3">
                <h4 class="category-bg">Category</h4>
                <div class="categories-checkbox">
                    @foreach (var category in Model)
                    {
                        <div>
                            <label>
                                <input type="checkbox" name="ChosenCategoriesIds" value="@category.Id" />
                                @category.Name
                            </label>
                        </div>
                    }
                </div>
            </div>
        }
        <div id="SearchResults" class="col-md-9">
            @this.Html.Action("InitialAds")
        </div>
    </div>
</div>

<input type="image" id="SpinnerGif" src="~/Content/Images/spinner.gif" />

@section Scripts {
    <script>
        $('.sort-ads-list li input[type="radio"]').change(function () {
            var $radio = $(this);
            if (!$radio.is(':checked')) {
                return;
            }

            $('#SearchForm').submit();
        });

        $('#SearchField').on('input', function () {
            var $searchField = $(this);

            if ($searchField.val().length === 0) {
                $('#SearchForm').submit();
            }
        });

        function onAjaxRequestBegin() {
            $('#SpinnerGif').show();
        }

        function onAjaxRequestComplete() {
            $('#SpinnerGif').hide();
        }
    </script>    
}

MyMarket/Web/MyMarket.Web/Views/Ads/Post.cshtml
@using MyMarket.Common;
@using MyMarket.Web.Models.Ad

@model AdCreateViewModel
@{
    ViewBag.Title = "Post Ad";
}

@section Styles {
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.3/summernote.css" rel="stylesheet" />
}

@if (this.User.Identity.IsAuthenticated)
{
    <h2>@ViewBag.Title</h2>

    using (Html.BeginForm("Post", "Ads", FormMethod.Post, new { id = "CreateAdForm", @class = "form-horizontal", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary("", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(a => a.Title, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(a => a.Title, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter title..." }})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(a => a.CategoryId, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.CategoryId, new SelectList(Model.Categories, "Id", "Name", 1), new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(a => a.Price, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(a => a.Price, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter price, e.g. 0.00 " }})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(a => a.Description, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(a => a.Description, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter description..." }})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(a => a.MainPicture, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(a => a.MainPicture, new { type = "file" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(a => a.OtherPictures, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                <div class="input-group">
                    <p>
                        @Html.TextBoxFor(a => a.OtherPictures, new { type = "file" })
                        @Html.TextBoxFor(a => a.OtherPictures, new { type = "file" })
                        @Html.TextBoxFor(a => a.OtherPictures, new { type = "file" })
                    </p>
                    <p>
                        <strong>
                            Allowed formats:
                            @ValidationConstants.JPG_IMAGE,
                            @ValidationConstants.JPEG_IMAGE,
                            @ValidationConstants.PNG_IMAGE,
                            @ValidationConstants.GIF_IMAGE
                        </strong>
                        <br />
                        <strong>Maximum size: @ValidationConstants.AD_IMAGE_CONTENT_LENGTH_IN_KILOBYTES kb</strong>
                    </p>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-5 col-md-6">
                <input type="submit" class="btn btn-primary" value="Create" />
                <input type="reset" class="btn btn-default" value="Clear" />
            </div>
        </div>
    }
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.3/summernote.js"></script>
    <script>
        $(document).ready(function () {
            $('#Description').summernote({
                minHeight: 400,
                maxHeight: 400
            });
        });
    </script>
}